---
name: dev-deployment

on:
  push:
    branches:
      - main

jobs:
  dockerbuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWOD }}
      
      - name: short commit tag
        run : echo "short_tag=${GITHUB_SHA::7}" >> $GITHUB_ENV 


      - name: Build and push Docker images
        uses: docker/build-push-action@v7.4.0
        with:
          context: ./app
          push: true
          tags: |
              ${{ vars.DOCKER_USERNAME }}/web-app3:${{ env.short_tag }}
              ${{ vars.DOCKER_USERNAME }}/web-app3:${{ env.short_tag }}

      
  Deploy:
    runs-on: ubuntu-latest
    needs: dockerbuild
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: setup for ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy compose file to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ vars.EC2_USER }}@${{ vars.EC2_HOST }} "mkdir -p ~/ali-final-task/app"
          scp -i ~/.ssh/id_rsa app/docker-compose.yml ${{ vars.EC2_USER }}@${{ vars.EC2_HOST }}:~/ali-final-task/app/

      - name: Deploy to EC2
        run: |
            ssh -i ~/.ssh/id_rsa ${{ vars.EC2_USER }}@${{ vars.EC2_HOST }} << EOF
            set -e
            cd ~/ali-final-task/app
            export DOCKER_USERNAME=${{ vars.DOCKER_USERNAME }}
            export IMAGE_TAG=${{ env.short_tag }}
            sudo -E docker compose pull
            sudo -E docker compose up -d
            EOF